#ENC[AES256_GCM,data:09cF102zQuWFDNmxDUyqokoOwVia,iv:4GWSNSyxMsZXjLbuw27lPYO5Hm/kxu2+m/c7f/6KCEY=,tag:Lx0KIzETV/6sUVEmcQb0Ag==,type:comment]
cluster:
    name: ENC[AES256_GCM,data:uzdbDQ9/aN4IqKbH,iv:juGUz2H1lsh8tpBwJmSEmZ5O1a1CgTdYfwf4z9VGEVg=,tag:B90DquInd4EnqeZ0TQTgng==,type:str]
sops:
    age:
        - recipient: age1y2femads2lfd67eetruaexrk5dn4p5840fjvfgqnagfjdxy70plstkfy98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad2R5a1paK1BvVGJMQnFS
            Zmxpbm1MNlpMeEM0OU01T3lVYmRpTHcvU2c0ClU2Ym9EMkpCQnNFM1ljdk5OVnV6
            eXhaNnRkTkk1Wm1nYXVVL2NKeTBhaTgKLS0tIHhpd3Q0VUtOeDA0SnBQUUt2enl0
            Q2FUaU1MK00zdmp2WkZSTCt3QUlVLzQK8iWKV5JB81G0JWRopSq5lmMmsJae1an0
            Pr8UgNQKKrGwaK3uZ7RaNlfxgBk+0crCvcqS6CbaXjlTa7ZXbcK9Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-05T05:37:11Z"
    mac: ENC[AES256_GCM,data:50328cA/6HONJmWfFfczEM4E20QcUUUGD7NrfZ8PwwsL1PAdoocTMlF6i/Ut1EMX9K4NJF+89LxW9EFmjSaBV0ML5uG3KoU9424E39+ir1m6fcf6rBLpl81W3MDzyNGUWtD3E9XjS4MqU9+zx1n//S2yVtx4vAjmN679qfvqsg8=,iv:8KxonWJt6pRaBrx9+kQ8C+lUYxHowbW0PAsCcEWxYf4=,tag:UezNcg+3ghGBoF7k2jiSwQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2